services:
  go:
    image: "mcr.microsoft.com/devcontainers/go:1-1.22-bookworm"
    volumes:
      - ./:/go/src/app
    ports:
      - 3000:3000
      - 5000:5000
    tty:  true
    depends_on:
      - db
    env_file:
      - ./dotenv/.env
  db:
    image: postgres:16
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./backup:/docker-entrypoint-initdb.d 
    ports:
      - 2345:5432
    env_file:
      - ./dotenv/.env